### PR TITLE
remove the use of querySelectorAll()

### PR DESCRIPTION
**Pull request by remi-grumeau**
We only need it for an easy selection, so let's not use it, that would improve our support for WindowsPhone & old browsers (Blackberry 5, old Opera, ...)

### CODE REVIEW

**Comment by msgilligan** [comment]
I should have tested before pulling.  This code required the following fix:
https://github.com/iui/iUI/commit/2b2a2d7719e69675ea862429ac64fea8b51d14c5

**Comment by remi-grumeau** [comment]
humm... the use of splice() was to avoid a new array but if it works, i'm good with that! 
At least it's done.

To replicate in iui-eventlog.js

Remi

**Comment by msgilligan** [comment]
The children "array" is not a "real" array and is read-only.  So to remove elements, we have to copy.  (If it did allow us to remove elements, they would be removed from the DOM because it is a "live" view.)

What do you mean by "to replicate in iui-eventlog.js"?

(Please note that I did update the extensions to use iui.getAllViews() wherever possible: https://github.com/iui/iUI/commit/6d7afe0951f68357089ef3412b83cb62332fb97f)

**Comment by remi-grumeau** [comment]
> The children "array" is not a "real" array and is read-only. So to remove elements, we have to copy. (If it did allow us to remove elements, they would be removed from the DOM because it is a "live" view.)

ok.

> What do you mean by "to replicate in iui-eventlog.js"?
> 
> (Please note that I did update the extensions to use iui.getAllViews() wherever possible: 

yes, you already did:
https://github.com/iui/iUI/commit/29eefc57193c5d45b8e225a57fb037c6720dd71b#web-app/iui/js/iui-event-log.js

Sounds all good to me! :)

**Comment by msgilligan** [comment]
While looking at the extensions today, I looked into something I'd been wondering about for a while and made this set of changes: https://github.com/iui/iUI/pull/6

I'm not sure what this could break, but it's a much better way of doing things.  Go check it out...

**Pull request merged**
