### PR TITLE
Proposed fix for broken gaeDeploy.sh script (per discussion today)

### PR DESCRIPTION
**Pull request by truedat101**
Invocation of ./gradlew gaeUpload
fails with srcDirs path not found.  It appears the gradle-gae-plugin
(https://github.com/bmuschko/gradle-gae-plugin) has changed how it sets
both srcDirs and warDir with Gaelyk 1.2.  In commit: 3df134 on iUi,
the transition to Gaelyk 1.2 takes place.  This is a big deal and
affects the entire gaelyk build.  I believe, based on review of the
above github URL, that there is a bug in the gradle gae plugin that
always uses the default srcDirs path 'src/main/webapp' to find
WEB-INF/groovy.  I was unable to coerce the build.gradle to use
anything other than the expected default gradle directory structure.
So that it uses the default directory isn't a problem, but the problem
was that I couldn't override the srcDirs property.  I will explore this
later.

The quick fix is to add a soft link to 'src/main/webapp' ->../../web-app

This begs the question, why not adopt the proper gradle directory
structure?  So I see this fix as a workaround until we answer the real
question.

### CODE REVIEW

**Comment by msgilligan** [comment]
Thanks, again.  I deployed the latest to http://demo.iui-js.org using this commit!

**Comment by msgilligan** [comment]
The proper Gradle structure puts all the important content too deep in the folder hierarchy.  In fact, I want to reconfigure the project so that everything from web-app is in the root directory!  I don't know if that can be made to work and I know it is heresy to a Java guy, but for the iUI community it would be the best thing if index.html in the root of the project is index.html on http://demo.iui-js.org, etc.

I'm willing to harras the GAE and Gaelyk plugin authors to get this working -- just not ready for that yet.

I want to do a directory cleanup/re-org in release 0.5 so the time is getting near for this change.  Do you want to make a branch and see if you can get it working?  :)

**Comment by msgilligan** [comment]
Haha.  I just tried your symlink trick on another project where I was trying to put webapp in the root.  I wasn't thinking too clearly and created a link cycle...

**Comment by truedat101** [comment]
Nice, I'll create an issue (I guess in the google code part of the project) to add an RFE for directory structure changes.  I don't know that problems are with gaeylk or grade so much as they are with my knowledge of groovy and scope and execution ordering of these build files.  Either way, sym link haxie is ok for now, but may not work well on a windows machine (some system calls don't follow sym links).  I agree on reorganizing the directory structure to put web-app at the root of the dir structure.  All build systems other than make and ant seem to enforce conventions that are helpful, but only for prototypical directory structure.  I often have to support automation of builds for Eclipse projects, and I hit this issue all the time ... wedge an Eclipse directory structure into a maven or ant build.

**Comment by msgilligan** [comment]
Great!  I'd definitely like to keep issue tracking for iUI in Google Code for now.  I actually like their issue tracker and we've got a whole lot of valuable content in it (that we need to do a better job of processing.)

I already added this issue on the gradle-gae-plugin, by the way:
https://github.com/bmuschko/gradle-gae-plugin/issues/30

**Pull request merged**
