### PR TITLE
Html cleanup

### PR DESCRIPTION
**Pull request by remi-grumeau**

### CODE REVIEW

**Comment by msgilligan** [comment]
I see you added an HTML cleanup branch.  Thanks for doing that!

But... The HTML cleanup branch should not have the Full Page HTML changes to iui.js in it _and_ it should be in sync with the latest code on "master"  (i.e. it should show up in the network graph as a node with a single arrow from the latest 'master')

**Comment by remi-grumeau** [comment]
So the branch functionality in Github of Mac sounds broken...

**Comment by msgilligan** [comment]
Try using the command line:
git checkout -b remi-htmlcleanup

**Comment by remi-grumeau** [comment]
My bad, i shouldn't have done anything before a 0.4 release.
Please (continue) to ignore all this work, and continue what you're doing.

**Comment by msgilligan** [comment]
No problem, Remi.  I know this has been frustrating for you.  I appreciate your patience.  Truly!

**Comment by remi-grumeau** [comment]
just don't want to loose anymore time.

**Comment by msgilligan** [comment]
This pull request is rejected because it includes "Full Page HTML changes to iui.js" as mentioned above.  (It also cannot be automatically merged.)

Full page HTML support should be developed as an iUI extension using the iUI extension mechanism.  It is a use case that the "iui.beforeinsert" event was designed for.  This has also been discussed on the iui-developers list.

**Pull request closed without merging**
