### PR TITLE
HTML header cleanup

### PR DESCRIPTION
**Pull request by remi-grumeau**

### CODE REVIEW

**Comment by msgilligan** [comment]
Hmm...  I wrote a comment listing 4 specific reason for not accepting this pull request, but it seems I did it wrong or GitHub lost it.

Although I had asked that we wait for 0.5 before doing the header cleanup, I would strongly consider making it part of 0.4 if it were submitted as a standalone patch (i.e. without the full-page HTML patch)

**Comment by msgilligan** [comment]
I guess when I clicked the "Close" button GitHub threw away (without warning, it seems) the text I had entered in a "Comments" text box...

**Comment by msgilligan** [comment]
The 4 reasons were:

1) The request is not in a branch that is in sync with the current 'master'
2) The request contains more than one change and should be two separate requests
3) The first change, full HTML page ajax, should be an extension not a change to core
4) The 2nd change, HTML header cleanup should probably wait for 0.5, but if you submit it as a separate change, I'm likely to change my mind on it.

**Comment by remi-grumeau** [comment]
1) ok
2) ok
3) not ok
4) ok. i'm not.

**Comment by msgilligan** [comment]
Sounds good.

As for (3).  Remember I will write a tool for 0.5 that merges the Full-page-HTML extension into a single .js file.  The code will be cleaner and more maintainable this way.  But we can discuss this more after 0.4 ships.

**Pull request closed without merging**
